import JSZip from "jszip";
import { NextResponse } from "next/server";

type FileItem = {
  path: string;
  content: string;
};

function normalizePath(filePath: string) {
  return filePath
    .replace(/^\/+/, "")
    .replace(/\.\./g, "")
    .replace(/\\/g, "/")
    .trim();
}

function parseFiles(text?: string): FileItem[] {
  if (!text || typeof text !== "string") {
    return [];
  }

  const files: FileItem[] = [];
  const parts = text.split("FILE:");

  for (let part of parts) {
    part = part.trim();
    if (!part) continue;

    const firstLineEnd = part.indexOf("\n");

    if (firstLineEnd === -1) {
      continue;
    }

    const filePath = part.substring(0, firstLineEnd).trim();
    const content = part.substring(firstLineEnd).trim();

    if (!filePath || !content) {
      continue;
    }

    files.push({
      path: normalizePath(filePath),
      content,
    });
  }

  return files;
}

function hasFile(files: FileItem[], path: string) {
  return files.some((file) => file.path === path);
}

function removeFiles(files: FileItem[], paths: string[]) {
  return files.filter((file) => !paths.includes(file.path));
}

function safePackageJson() {
  return JSON.stringify(
    {
      name: "founder-ai-generated-project",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "14.2.23",
        react: "18.3.1",
        "react-dom": "18.3.1",
      },
      devDependencies: {
        "@types/node": "20.17.12",
        "@types/react": "18.3.18",
        "@types/react-dom": "18.3.5",
        typescript: "5.7.2",
        tailwindcss: "3.4.17",
        postcss: "8.4.49",
        autoprefixer: "10.4.20",
        eslint: "8.57.1",
        "eslint-config-next": "14.2.23",
      },
    },
    null,
    2
  );
}

function normalizePackageJson(content: string) {
  try {
    const pkg = JSON.parse(content);

    return JSON.stringify(
      {
        ...pkg,
        scripts: {
          ...(pkg.scripts || {}),
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          ...(pkg.dependencies || {}),
          next: "14.2.23",
          react: "18.3.1",
          "react-dom": "18.3.1",
        },
        devDependencies: {
          ...(pkg.devDependencies || {}),
          "@types/node": "20.17.12",
          "@types/react": "18.3.18",
          "@types/react-dom": "18.3.5",
          typescript: "5.7.2",
          tailwindcss: "3.4.17",
          postcss: "8.4.49",
          autoprefixer: "10.4.20",
          eslint: "8.57.1",
          "eslint-config-next": "14.2.23",
        },
      },
      null,
      2
    );
  } catch {
    return safePackageJson();
  }
}

function ensureBaseFiles(files: FileItem[]) {
  let finalFiles = [...files];

  finalFiles = removeFiles(finalFiles, ["next.config.ts", "next.config.js"]);

  finalFiles = finalFiles.map((file) => {
    const safePath = normalizePath(file.path);

    if (safePath === "package.json") {
      return {
        path: safePath,
        content: normalizePackageJson(file.content),
      };
    }

    return {
      path: safePath,
      content: file.content,
    };
  });

  if (!hasFile(finalFiles, "package.json")) {
    finalFiles.push({
      path: "package.json",
      content: safePackageJson(),
    });
  }

  if (!hasFile(finalFiles, "tsconfig.json")) {
    finalFiles.push({
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2017",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: false,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [
              {
                name: "next",
              },
            ],
            paths: {
              "@/*": ["./*"],
            },
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"],
        },
        null,
        2
      ),
    });
  }

  if (!hasFile(finalFiles, "next-env.d.ts")) {
    finalFiles.push({
      path: "next-env.d.ts",
      content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file was generated by Founder AI.
`,
    });
  }

  if (!hasFile(finalFiles, "next.config.mjs")) {
    finalFiles.push({
      path: "next.config.mjs",
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`,
    });
  }

  if (!hasFile(finalFiles, "postcss.config.mjs")) {
    finalFiles.push({
      path: "postcss.config.mjs",
      content: `const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`,
    });
  }

  if (!hasFile(finalFiles, "tailwind.config.ts")) {
    finalFiles.push({
      path: "tailwind.config.ts",
      content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,
    });
  }

  if (!hasFile(finalFiles, "app/globals.css")) {
    finalFiles.push({
      path: "app/globals.css",
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: white;
  color: #111111;
}
`,
    });
  }

  if (!hasFile(finalFiles, "app/layout.tsx")) {
    finalFiles.push({
      path: "app/layout.tsx",
      content: `import "./globals.css";

export const metadata = {
  title: "Founder AI Generated Project",
  description: "Generated by Founder AI Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    });
  }

  if (!hasFile(finalFiles, "app/page.tsx")) {
    finalFiles.push({
      path: "app/page.tsx",
      content: `export default function Home() {
  return (
    <main className="min-h-screen bg-white px-6 py-12 text-black">
      <div className="mx-auto max-w-4xl">
        <p className="text-sm font-medium text-gray-500">
          Generated by Founder AI
        </p>

        <h1 className="mt-4 text-5xl font-bold tracking-tight">
          Generated Project
        </h1>

        <p className="mt-5 text-lg leading-8 text-gray-600">
          This project was generated by Founder AI. Replace this page with your
          final product experience.
        </p>
      </div>
    </main>
  );
}
`,
    });
  }

  if (!hasFile(finalFiles, "README.md")) {
    finalFiles.push({
      path: "README.md",
      content: `# Founder AI Generated Project

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open:

\`\`\`txt
http://localhost:3000
\`\`\`

## Generated by Founder AI

This project was generated as a runnable Next.js starter.
`,
    });
  }

  if (!hasFile(finalFiles, ".gitignore")) {
    finalFiles.push({
      path: ".gitignore",
      content: `node_modules
.next
.env
.env.local
.DS_Store
`,
    });
  }

  return finalFiles;
}

export async function POST(req: Request) {
  try {
    const { result, files } = await req.json();

    let parsedFiles: FileItem[] = [];

    if (Array.isArray(files)) {
      parsedFiles = files.map((file) => ({
        path: normalizePath(file.path),
        content: String(file.content || ""),
      }));
    } else {
      parsedFiles = parseFiles(result);
    }

    if (parsedFiles.length === 0) {
      return NextResponse.json(
        { error: "No valid project files found." },
        { status: 400 }
      );
    }

    const finalFiles = ensureBaseFiles(parsedFiles);
    const zip = new JSZip();

    for (const file of finalFiles) {
      zip.file(file.path, file.content);
    }

    const blob = await zip.generateAsync({ type: "arraybuffer" });

    return new NextResponse(blob, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition":
          'attachment; filename="founder-ai-generated-project.zip"',
      },
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}