// Generates a downloadable multi-file Next.js starter project.
// This is the first real "build output" layer for Founder AI.

import JSZip from "jszip";
import { NextResponse } from "next/server";

function safeText(value: string) {
  return value.replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

export async function POST(req: Request) {
  try {
    const { idea, result } = await req.json();

    if (!idea || !result) {
      return NextResponse.json(
        { error: "Missing idea or result." },
        { status: 400 }
      );
    }

    const zip = new JSZip();

    zip.file(
      "README.md",
      `# Founder AI Generated Project

## Idea

${idea}

## What Founder AI generated

${result}

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open:

\`\`\`txt
http://localhost:3000
\`\`\`
`
    );

    zip.file(
      "package.json",
      JSON.stringify(
        {
          name: "founder-ai-generated-project",
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint",
          },
          dependencies: {
            "@supabase/supabase-js": "latest",
            next: "latest",
            react: "latest",
            "react-dom": "latest",
            stripe: "latest",
          },
          devDependencies: {
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            typescript: "latest",
            tailwindcss: "latest",
            postcss: "latest",
            autoprefixer: "latest",
          },
        },
        null,
        2
      )
    );

    zip.file(
      ".env.example",
      `NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_APP_URL=http://localhost:3000
`
    );

    zip.file(
      "app/layout.tsx",
      `import "./globals.css";

export const metadata = {
  title: "Generated by Founder AI",
  description: "A generated project scaffold from Founder AI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
    );

    zip.file(
      "app/globals.css",
      `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background: white;
  color: black;
}
`
    );

    zip.file(
      "tailwind.config.ts",
      `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`
    );

    zip.file(
      "postcss.config.mjs",
      `const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`
    );

    zip.file(
      "lib/supabase.ts",
      `import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);
`
    );

    zip.file(
      "lib/stripe.ts",
      `import Stripe from "stripe";

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);
`
    );

    zip.file(
      "components/Hero.tsx",
      `export default function Hero() {
  return (
    <section className="rounded-3xl border bg-gray-50 p-10">
      <p className="text-sm font-medium text-gray-500">Generated by Founder AI</p>

      <h1 className="mt-4 max-w-3xl text-5xl font-bold tracking-tight">
        ${safeText(idea)}
      </h1>

      <p className="mt-5 max-w-2xl text-lg text-gray-600">
        This starter project was generated from your idea and includes a clean
        foundation for turning it into a real product.
      </p>

      <div className="mt-8 flex gap-3">
        <a
          href="#plan"
          className="rounded-xl bg-black px-5 py-3 text-white"
        >
          View Build Plan
        </a>

        <a
          href="#stack"
          className="rounded-xl border px-5 py-3"
        >
          Tech Stack
        </a>
      </div>
    </section>
  );
}
`
    );

    zip.file(
      "components/BuildPlan.tsx",
      `export default function BuildPlan() {
  return (
    <section id="plan" className="mt-10 rounded-3xl border p-8">
      <h2 className="text-2xl font-bold">Founder AI Build Plan</h2>

      <div className="mt-5 whitespace-pre-wrap text-sm leading-7 text-gray-700">
        {\\`${safeText(result)}\\`}
      </div>
    </section>
  );
}
`
    );

    zip.file(
      "components/Stack.tsx",
      `export default function Stack() {
  const items = [
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "Supabase",
    "Stripe",
    "Vercel",
  ];

  return (
    <section id="stack" className="mt-10 rounded-3xl border p-8">
      <h2 className="text-2xl font-bold">Recommended Stack</h2>

      <div className="mt-5 grid gap-3 sm:grid-cols-2 md:grid-cols-3">
        {items.map((item) => (
          <div key={item} className="rounded-xl bg-gray-50 p-4 text-sm">
            {item}
          </div>
        ))}
      </div>
    </section>
  );
}
`
    );

    zip.file(
      "app/page.tsx",
      `import Hero from "@/components/Hero";
import BuildPlan from "@/components/BuildPlan";
import Stack from "@/components/Stack";

export default function Home() {
  return (
    <main className="min-h-screen px-6 py-10">
      <div className="mx-auto max-w-6xl">
        <Hero />
        <Stack />
        <BuildPlan />
      </div>
    </main>
  );
}
`
    );

    zip.file(
      "app/api/health/route.ts",
      `export async function GET() {
  return Response.json({
    status: "ok",
    message: "Generated project is running.",
  });
}
`
    );

    zip.file(
      "app/api/checkout/route.ts",
      `import { stripe } from "@/lib/stripe";

export async function POST() {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

  const session = await stripe.checkout.sessions.create({
    mode: "payment",
    payment_method_types: ["card"],
    line_items: [
      {
        price_data: {
          currency: "usd",
          product_data: {
            name: "Generated Product",
          },
          unit_amount: 1000,
        },
        quantity: 1,
      },
    ],
    success_url: appUrl,
    cancel_url: appUrl,
  });

  return Response.json({ url: session.url });
}
`
    );

    zip.file(
      "DATABASE.md",
      `# Suggested Database Tables

## users
Managed by Supabase Auth.

## projects
- id uuid primary key
- user_id uuid
- title text
- description text
- created_at timestamp

## subscriptions
- id uuid primary key
- user_id uuid
- stripe_customer_id text
- stripe_subscription_id text
- status text
- created_at timestamp
`
    );

    zip.file(
      "DEPLOYMENT.md",
      `# Deployment Guide

## 1. Create Supabase project

Add environment variables:

\`\`\`txt
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
\`\`\`

## 2. Create Stripe keys

Add:

\`\`\`txt
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
\`\`\`

## 3. Deploy to Vercel

Push to GitHub, import repo in Vercel, add environment variables, deploy.

## 4. Test

\`\`\`bash
npm run dev
\`\`\`
`
    );

    const content = await zip.generateAsync({ type: "arraybuffer" });

    return new NextResponse(content, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition":
          'attachment; filename="founder-ai-generated-project.zip"',
      },
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}