import { NextResponse } from "next/server";
import { existsSync } from "fs";
import { copyFile, mkdir, rm, writeFile } from "fs/promises";
import path from "path";
import { execa } from "execa";
import { v4 as uuidv4 } from "uuid";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type FileItem = {
  path: string;
  content: string;
};

function normalizePath(filePath: string) {
  return filePath
    .replace(/^\/+/, "")
    .replace(/\.\./g, "")
    .replace(/\\/g, "/")
    .trim();
}

function hasFile(files: FileItem[], filePath: string) {
  return files.some((file) => file.path === filePath);
}

function ensureBaseFiles(files: FileItem[]) {
  const finalFiles = [...files];

  if (!hasFile(finalFiles, "package.json")) {
    finalFiles.push({
      path: "package.json",
      content: JSON.stringify(
        {
          name: "founder-ai-preview-project",
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev -H 0.0.0.0",
            build: "next build",
            start: "next start -H 0.0.0.0",
          },
          dependencies: {
            next: "latest",
            react: "latest",
            "react-dom": "latest",
          },
          devDependencies: {
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            typescript: "latest",
            tailwindcss: "latest",
            postcss: "latest",
            autoprefixer: "latest",
          },
        },
        null,
        2
      ),
    });
  }

  if (!hasFile(finalFiles, "app/page.tsx")) {
    finalFiles.push({
      path: "app/page.tsx",
      content: `export default function Home() {
  return (
    <main className="min-h-screen bg-white px-6 py-12 text-black">
      <h1 className="text-4xl font-bold">Founder AI Preview</h1>

      <p className="mt-4 text-gray-600">
        No generated page was found, so Founder AI created this fallback page.
      </p>
    </main>
  );
}
`,
    });
  }

  if (!hasFile(finalFiles, "app/layout.tsx")) {
    finalFiles.push({
      path: "app/layout.tsx",
      content: `import "./globals.css";

export const metadata = {
  title: "Founder AI Preview",
  description: "Preview generated by Founder AI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    });
  }

  if (!hasFile(finalFiles, "app/globals.css")) {
    finalFiles.push({
      path: "app/globals.css",
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  background: white;
  color: #111111;
}
`,
    });
  }

  if (!hasFile(finalFiles, "postcss.config.mjs")) {
    finalFiles.push({
      path: "postcss.config.mjs",
      content: `const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`,
    });
  }

  if (!hasFile(finalFiles, "tailwind.config.ts")) {
    finalFiles.push({
      path: "tailwind.config.ts",
      content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,
    });
  }

  if (!hasFile(finalFiles, "tsconfig.json")) {
    finalFiles.push({
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2017",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            paths: {
              "@/*": ["./*"],
            },
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"],
        },
        null,
        2
      ),
    });
  }

  if (!hasFile(finalFiles, "next.config.ts")) {
    finalFiles.push({
      path: "next.config.ts",
      content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`,
    });
  }

  return finalFiles;
}

async function writeProjectFiles(projectPath: string, files: FileItem[]) {
  await mkdir(projectPath, { recursive: true });

  for (const file of files) {
    if (!file.path) continue;

    const fullPath = path.join(projectPath, file.path);

    if (!fullPath.startsWith(projectPath)) {
      continue;
    }

    await mkdir(path.dirname(fullPath), { recursive: true });
    await writeFile(fullPath, file.content);
  }
}

async function writeDockerfile(projectPath: string) {
  const dockerfilePath = path.join(process.cwd(), "sandbox/Dockerfile");
  const targetDockerfilePath = path.join(projectPath, "Dockerfile");

  if (existsSync(dockerfilePath)) {
    await copyFile(dockerfilePath, targetDockerfilePath);
    return;
  }

  await writeFile(
    targetDockerfilePath,
    `FROM node:18-alpine

WORKDIR /app

COPY . .

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
`
  );
}

export async function POST(req: Request) {
  try {
    if (process.env.VERCEL === "1") {
      return NextResponse.json(
        {
          error:
            "Live Docker preview is disabled on Vercel. Use Download ZIP, or run preview locally. Production previews require a separate Docker worker service.",
          preview_available: false,
        },
        { status: 501 }
      );
    }

    const { files } = await req.json();

    if (!Array.isArray(files) || files.length === 0) {
      return NextResponse.json(
        { error: "No files provided." },
        { status: 400 }
      );
    }

    const safeFiles = files.map((file) => ({
      path: normalizePath(String(file.path || "")),
      content: String(file.content || ""),
    }));

    const finalFiles = ensureBaseFiles(safeFiles);

    const id = uuidv4();
    const projectPath = path.join(process.cwd(), "tmp", id);

    await writeProjectFiles(projectPath, finalFiles);
    await writeDockerfile(projectPath);

    const port = 4000 + Math.floor(Math.random() * 1000);
    const containerName = `founder-preview-${id}`;

    await execa("docker", ["build", "-t", containerName, "."], {
      cwd: projectPath,
    });

    await execa("docker", [
      "run",
      "-d",
      "--name",
      containerName,
      "-p",
      `${port}:3000`,
      "--memory=512m",
      "--cpus=1",
      containerName,
    ]);

    setTimeout(async () => {
      try {
        await execa("docker", ["rm", "-f", containerName]);
        await rm(projectPath, { recursive: true, force: true });
      } catch {
        // Quiet cleanup. Docker is already dramatic enough.
      }
    }, 5 * 60 * 1000);

    return NextResponse.json({
      url: `http://localhost:${port}`,
      container: containerName,
      preview_available: true,
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}