import { createClient } from "@supabase/supabase-js";
import OpenAI from "openai";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

async function getAuthenticatedUser(req: Request) {
  const authHeader = req.headers.get("authorization");

  if (!authHeader?.startsWith("Bearer ")) {
    return null;
  }

  const token = authHeader.replace("Bearer ", "");

  const {
    data: { user },
    error,
  } = await supabaseAdmin.auth.getUser(token);

  if (error || !user) {
    return null;
  }

  return user;
}

function getBuilderSystemPrompt() {
  return `
You are Founder AI Builder, a senior full-stack engineer and product operator.

Your task is to generate a complete runnable project using MULTI-FILE OUTPUT.

The product must help the user build real websites, full-stack web apps, Shopify stores, Shopify apps, marketing systems, and sales workflows.

CRITICAL OUTPUT FORMAT:
You MUST output files using this exact format:

FILE: package.json
<file contents>

FILE: app/page.tsx
<file contents>

FILE: app/layout.tsx
<file contents>

Do not wrap file contents in markdown fences.
Do not write explanations outside files.
Do not say "Here is".
Do not include commentary.
Only output FILE blocks.

MANDATORY FILES:
You must always include at least these files:

FILE: package.json
FILE: app/layout.tsx
FILE: app/page.tsx
FILE: app/globals.css
FILE: components/Hero.tsx
FILE: components/FeatureGrid.tsx
FILE: components/CTA.tsx
FILE: lib/config.ts
FILE: README.md

TECH RULES:
- Use Next.js App Router.
- Use TypeScript.
- Use Tailwind CSS classes.
- Use React Server Components unless interactivity is needed.
- Keep code simple and runnable.
- Do not require external paid APIs unless clearly placed behind env vars.
- Use clean, modern UI.
- No placeholder lorem ipsum.
- No broken imports.
- Every imported file must exist.
- package.json must include dependencies required by the generated code.
- The generated app must run with:
  npm install
  npm run dev

PRODUCT RULES:
If the user asks for a website:
- Generate a landing page with sections, copy, CTA, and SEO-minded structure.

If the user asks for a full-stack app:
- Include app pages, API routes, simple data model notes, and auth/payment placeholders where useful.

If the user asks for a Shopify store:
- Generate store strategy, collection/page structure, product page copy, theme-like sections, and launch checklist as app content.

If the user asks for a Shopify app:
- Include Shopify OAuth notes, embedded admin structure, billing placeholder, webhook placeholder, and theme extension notes.

If the user asks for marketing/sales:
- Generate campaign pages, ICP, offer, outreach sequence, ad copy, and execution plan inside the app.

QUALITY BAR:
The result should feel like the first working version of a real product, not a school assignment.

Remember:
ONLY FILE OUTPUT.
No markdown code fences.
No explanations outside FILE blocks.
`;
}

function fallbackProject(idea: string) {
  const safeIdea = idea.replace(/`/g, "'").replace(/\$/g, "\\$");

  return `FILE: package.json
{
  "name": "founder-ai-generated-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "typescript": "latest",
    "tailwindcss": "latest",
    "postcss": "latest",
    "autoprefixer": "latest"
  }
}

FILE: app/layout.tsx
import "./globals.css";

export const metadata = {
  title: "Founder AI Generated Project",
  description: "Generated by Founder AI Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

FILE: app/page.tsx
import Hero from "@/components/Hero";
import FeatureGrid from "@/components/FeatureGrid";
import CTA from "@/components/CTA";

export default function Home() {
  return (
    <main className="min-h-screen bg-white text-black">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <Hero />
        <FeatureGrid />
        <CTA />
      </div>
    </main>
  );
}

FILE: app/globals.css
@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: #ffffff;
  color: #111111;
}

FILE: components/Hero.tsx
import { appConfig } from "@/lib/config";

export default function Hero() {
  return (
    <section className="rounded-3xl border border-gray-200 bg-gray-50 px-8 py-16">
      <p className="text-sm font-semibold uppercase tracking-wide text-gray-500">
        Generated by Founder AI
      </p>

      <h1 className="mt-4 max-w-4xl text-5xl font-bold tracking-tight">
        {appConfig.name}
      </h1>

      <p className="mt-5 max-w-2xl text-lg leading-8 text-gray-600">
        {appConfig.description}
      </p>

      <div className="mt-8 flex flex-wrap gap-3">
        <a
          href="#features"
          className="rounded-xl bg-black px-5 py-3 text-sm font-medium text-white"
        >
          Explore Features
        </a>

        <a
          href="#cta"
          className="rounded-xl border border-gray-300 px-5 py-3 text-sm font-medium"
        >
          Launch Plan
        </a>
      </div>
    </section>
  );
}

FILE: components/FeatureGrid.tsx
const features = [
  {
    title: "Product foundation",
    description: "Clear structure for turning the idea into a real product.",
  },
  {
    title: "Execution workflow",
    description: "A practical flow users can understand, use, and improve.",
  },
  {
    title: "Growth direction",
    description: "Built with acquisition, conversion, and retention in mind.",
  },
];

export default function FeatureGrid() {
  return (
    <section id="features" className="mt-10 grid gap-4 md:grid-cols-3">
      {features.map((feature) => (
        <div key={feature.title} className="rounded-2xl border border-gray-200 p-6">
          <h2 className="text-lg font-semibold">{feature.title}</h2>
          <p className="mt-3 text-sm leading-6 text-gray-600">
            {feature.description}
          </p>
        </div>
      ))}
    </section>
  );
}

FILE: components/CTA.tsx
export default function CTA() {
  return (
    <section id="cta" className="mt-10 rounded-3xl bg-black p-8 text-white">
      <h2 className="text-3xl font-bold">Ready to build?</h2>

      <p className="mt-3 max-w-2xl text-sm leading-6 text-gray-300">
        This generated starter gives you the first working structure. Extend it
        with auth, payments, database tables, marketing pages, and deployment.
      </p>

      <button className="mt-6 rounded-xl bg-white px-5 py-3 text-sm font-medium text-black">
        Start building
      </button>
    </section>
  );
}

FILE: lib/config.ts
export const appConfig = {
  name: "${safeIdea}",
  description:
    "A generated project starter based on the original idea. Use this as the foundation for the first production version.",
};

FILE: README.md
# Founder AI Generated Project

## Idea

${safeIdea}

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open:

\`\`\`txt
http://localhost:3000
\`\`\`

## Next steps

- Replace starter copy with final brand copy.
- Add Supabase auth if users need accounts.
- Add Stripe if payments are required.
- Deploy to Vercel.
`;
}

function hasValidFileOutput(text: string) {
  return text.includes("FILE:") && text.includes("package.json") && text.includes("app/page.tsx");
}

export async function POST(req: Request) {
  try {
    const user = await getAuthenticatedUser(req);

    if (!user) {
      return Response.json({ error: "Unauthorized." }, { status: 401 });
    }

    const { idea } = await req.json();

    if (!idea || typeof idea !== "string") {
      return Response.json({ error: "Missing idea." }, { status: 400 });
    }

    let { data: usage, error: usageError } = await supabaseAdmin
      .from("usage_limits")
      .select("*")
      .eq("user_id", user.id)
      .maybeSingle();

    if (usageError) {
      return Response.json({ error: usageError.message }, { status: 500 });
    }

    if (!usage) {
      const { data: newUsage, error: createUsageError } = await supabaseAdmin
        .from("usage_limits")
        .insert({
          user_id: user.id,
          generations: 0,
          plan: "free",
          subscription_status: "inactive",
        })
        .select("*")
        .single();

      if (createUsageError) {
        return Response.json({ error: createUsageError.message }, { status: 500 });
      }

      usage = newUsage;
    }

    const plan = usage.plan || "free";
    const generations = usage.generations || 0;

    if (plan === "free" && generations >= 5) {
      return Response.json(
        {
          error: "Free limit reached",
          upgrade: true,
        },
        { status: 403 }
      );
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      temperature: 0.3,
      messages: [
        {
          role: "system",
          content: getBuilderSystemPrompt(),
        },
        {
          role: "user",
          content: idea,
        },
      ],
    });

    let result = completion.choices[0]?.message?.content || "";

    if (!hasValidFileOutput(result)) {
      result = fallbackProject(idea);
    }

    const { error: updateError } = await supabaseAdmin
      .from("usage_limits")
      .update({
        generations: generations + 1,
      })
      .eq("user_id", user.id);

    if (updateError) {
      return Response.json({ error: updateError.message }, { status: 500 });
    }

    return Response.json({
      result,
      plan,
      remaining:
        plan === "pro" ? "unlimited" : Math.max(0, 5 - (generations + 1)),
    });
  } catch (error) {
    return Response.json({ error: String(error) }, { status: 500 });
  }
}