import { appConfig } from "@/lib/config";

export default function Hero() {
  return (
    <section className="rounded-3xl border border-gray-200 bg-gray-50 px-8 py-16">
      <p className="text-sm font-semibold uppercase tracking-wide text-gray-500">
        Generated by Founder AI
      </p>

      <h1 className="mt-4 max-w-4xl text-5xl font-bold tracking-tight text-gray-950">
        {appConfig.name}
      </h1>

      <p className="mt-5 max-w-2xl text-lg leading-8 text-gray-600">
        {appConfig.description}
      </p>

      <div className="mt-8 flex flex-wrap gap-3">
        <a
          href="#features"
          className="rounded-xl bg-black px-5 py-3 text-sm font-medium text-white"
        >
          Explore Features
        </a>

        <a
          href="#cta"
          className="rounded-xl border border-gray-300 px-5 py-3 text-sm font-medium text-gray-900"
        >
          Launch Plan
        </a>
      </div>
    </section>
  );
}