import "./globals.css";

export const metadata = {
  title: "Founder AI Generated Project",
  description: "Generated by Founder AI Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}